version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
    working_directory: ~/rails-5-2-sandbox
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: |
            curl https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt update
            sudo apt install google-chrome-stable

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Bundle Install
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Create DB
          command: bundle exec rake db:create db:schema:load --trace
      - run:
          name: Run Tests
          command: RAILS_ENV=test bundle exec rspec
      - store_test_results:
          path: /tmp/test-results
